/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaoDien;

import DataBase.DataProvider;
import Dao.PhongBanDao;
import Model.PhongBan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;

/**
 *
 * @author Tuan
 */
public class QuanLyPhongBan extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiPhongBan123
     */
    private ArrayList<PhongBan> PBList;
    DefaultTableModel phongbanDefaultTableModel;

    public QuanLyPhongBan() {
        initComponents();
        PhongBanDao pbd = new PhongBanDao();
        PBList = pbd.DSPhongBan();
        phongbanDefaultTableModel = (DefaultTableModel) tblphongban.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblphongban = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sdtphongbanTF = new javax.swing.JTextField();
        maphongbanTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenphongbanTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diachiphongbanTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        thempbBTN = new javax.swing.JButton();
        suapbBTN = new javax.swing.JButton();
        xoapbBTN = new javax.swing.JButton();
        timkiemCB = new javax.swing.JComboBox<>();
        DanhSachPhongBanBTN = new javax.swing.JButton();
        timkiempbBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        tblphongban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblphongban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Ðịa chỉ phòng ban  ", "Số điện thoại phòng ban "
            }
        ));
        tblphongban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphongbanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblphongban);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Số điện thoại phòng ban");

        sdtphongbanTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        maphongbanTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        maphongbanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maphongbanTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã phòng ban");

        tenphongbanTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tenphongbanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenphongbanTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Tên phòng ban");

        diachiphongbanTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        diachiphongbanTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diachiphongbanTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ðịa chỉ phòng ban");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diachiphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tenphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diachiphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sdtphongbanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        thempbBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        thempbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create-icon.png"))); // NOI18N
        thempbBTN.setText("Thêm");
        thempbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thempbBTNMouseClicked(evt);
            }
        });

        suapbBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suapbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-edit-icon-16.png"))); // NOI18N
        suapbBTN.setText("Sửa");
        suapbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suapbBTNMouseClicked(evt);
            }
        });
        suapbBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suapbBTNActionPerformed(evt);
            }
        });

        xoapbBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        xoapbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-delete-icon.png"))); // NOI18N
        xoapbBTN.setText("Xoá");
        xoapbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoapbBTNMouseClicked(evt);
            }
        });

        timkiemCB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timkiemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm theo mã phòng ban", "Tìm kiếm theo địa chỉ", "Tìm kiếm theo tên phòng ban" }));
        timkiemCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemCBMouseClicked(evt);
            }
        });
        timkiemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemCBActionPerformed(evt);
            }
        });

        DanhSachPhongBanBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DanhSachPhongBanBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-calendar-list-icon.png"))); // NOI18N
        DanhSachPhongBanBTN.setText("Hiển thị danh sách");
        DanhSachPhongBanBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhSachPhongBanBTNMouseClicked(evt);
            }
        });
        DanhSachPhongBanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachPhongBanBTNActionPerformed(evt);
            }
        });

        timkiempbBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timkiempbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_search.png"))); // NOI18N
        timkiempbBTN.setText(" Tìm kiếm ");
        timkiempbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiempbBTNMouseClicked(evt);
            }
        });
        timkiempbBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiempbBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timkiemCB, 0, 256, Short.MAX_VALUE)
                    .addComponent(timkiempbBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DanhSachPhongBanBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xoapbBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suapbBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thempbBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(thempbBTN)
                .addGap(18, 18, 18)
                .addComponent(suapbBTN)
                .addGap(18, 18, 18)
                .addComponent(xoapbBTN)
                .addGap(18, 18, 18)
                .addComponent(DanhSachPhongBanBTN)
                .addGap(18, 18, 18)
                .addComponent(timkiempbBTN)
                .addGap(18, 18, 18)
                .addComponent(timkiemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void timkiemCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemCBMouseClicked
        
    }//GEN-LAST:event_timkiemCBMouseClicked

    private void DanhSachPhongBanBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhSachPhongBanBTNMouseClicked
        
        phongbanDefaultTableModel.setRowCount(0);
        PBList.forEach(s -> phongbanDefaultTableModel.addRow(s.toObjects()));
    }//GEN-LAST:event_DanhSachPhongBanBTNMouseClicked

    private void timkiempbBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiempbBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiempbBTNActionPerformed

    private void timkiempbBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiempbBTNMouseClicked
        PhongBanDao pbd = new PhongBanDao();
        String choice = timkiemCB.getItemAt(timkiemCB.getSelectedIndex());
        if (choice.equals("Tìm kiếm theo mã phòng ban")) {
            String input = JOptionPane.showInputDialog(null, "Nhập mã phòng ban ");
            if (input != null && input.length() > 0) {
                if (pbd.timKiemIdPhongBan(input) != null) {
                    phongbanDefaultTableModel.setRowCount(0);
                    phongbanDefaultTableModel.addRow(pbd.timKiemIdPhongBan(input).toObjects());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Mã phòng ban không tồn tại ! ");
                }
            }
        } else if (choice.equals("Tìm kiếm theo địa chỉ")) {
            String input = JOptionPane.showInputDialog(this, "Nhập địa chỉ cần tìm");

            if (input != null && input.length() > 0) {
                if (pbd.searchByAddress(input).size() >= 0) {
                    phongbanDefaultTableModel.setRowCount(0);
                    pbd.searchByAddress(input).forEach(s -> phongbanDefaultTableModel.addRow(s.toObjects()));
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Địa chỉ không tồn tại !");
                }
            }
        } else if (choice.equals("Tìm kiếm theo tên phòng ban")) {
            String input = JOptionPane.showInputDialog(null, "Nhập tên phòng ban ");
            if (input != null && input.length() > 0) {
                if (pbd.timKiemTenPhongBan(input) != null) {
                    phongbanDefaultTableModel.setRowCount(0);
                    phongbanDefaultTableModel.addRow(pbd.timKiemTenPhongBan(input).toObjects());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Tên phòng ban không tồn tại  ! ");
                }
            }
        }
    }//GEN-LAST:event_timkiempbBTNMouseClicked

    private void xoapbBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoapbBTNMouseClicked
        PhongBanDao pbd = new PhongBanDao();
        PhongBan pb = new PhongBan();
        String mapb = JOptionPane.showInputDialog(null, "Nhập mã phòng ban cần xoá");
        pb.setMaPB(mapb);

        int remove = tblphongban.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá phòng ban có mã " + mapb);

        try {
            if (confirm == JOptionPane.YES_OPTION) {
                if (pbd.xoaPhongBan(mapb)) {
                    JOptionPane.showMessageDialog(null, "Xoá thành công!");
                    phongbanDefaultTableModel.removeRow(remove);
                } else {
                    JOptionPane.showMessageDialog(null, "Xoá thất bại!");
                }
            } else {

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_xoapbBTNMouseClicked

    private void suapbBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suapbBTNMouseClicked
        PhongBanDao pbd = new PhongBanDao();
        PhongBan pb = new PhongBan();
        pb.setMaPB(maphongbanTF.getText());
        pb.setNamePB(tenphongbanTF.getText());
        pb.setDcPB(diachiphongbanTF.getText());
        pb.setSdtPB(sdtphongbanTF.getText());

        if (maphongbanTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập mã phòng ban tour !");
            maphongbanTF.requestFocus();
        } else if (tenphongbanTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập tên phòng ban !");
            tenphongbanTF.requestFocus();
        } else if (sdtphongbanTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập Số điện thoại  !");
            sdtphongbanTF.requestFocus();
        } else if (diachiphongbanTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập địa chỉ !");
            diachiphongbanTF.requestFocus();
        } else {
            if (pbd.updatePhongBan(pb)) {
                JOptionPane.showMessageDialog(null, "Sửa Thành Công!");
                int i = tblphongban.getSelectedRow();
                if (i >= 0) {
                    phongbanDefaultTableModel.setValueAt(tenphongbanTF.getText(), i, 1);
                    phongbanDefaultTableModel.setValueAt(diachiphongbanTF.getText(), i, 2);
                    phongbanDefaultTableModel.setValueAt(sdtphongbanTF.getText(), i, 3);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }
            resetThongTin();
        }
    }//GEN-LAST:event_suapbBTNMouseClicked

    private void thempbBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thempbBTNMouseClicked
        PhongBanDao pbd = new PhongBanDao();
        String ma = maphongbanTF.getText();
        String name = tenphongbanTF.getText();
        String diachi = diachiphongbanTF.getText();
        String sdt = sdtphongbanTF.getText();
        try {
            if (ma.equals("") || name.equals("") || diachi.equals("") || sdt.equals("")) {
                JOptionPane.showMessageDialog(null, "Không được để trống !");
                return;
            }
            PhongBan phongBan = new PhongBan(ma, name, diachi, sdt);
            for (PhongBan pb : PBList) {
                if (phongBan.trungMa(pb)) {
                    JOptionPane.showMessageDialog(null, "Mã đã tồn tại . Vui lòng nhập mã khác !");
                    return;
                }
                if (phongBan.trungName(pb)) {
                    JOptionPane.showMessageDialog(null, "Tên đã tồn tại . Vui lòng nhập tên khác !");
                    return;
                }
                if (phongBan.trungSDT(pb)) {
                    JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại . Vui lòng nhập số điện thoại khác !");
                    return;
                }
            }
            if (pbd.themphongban(phongBan)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công !");
                phongbanDefaultTableModel.addRow(phongBan.toObjects());
            } else {
                JOptionPane.showMessageDialog(null, "Mã đã tồn tại ! ");
            }
        } catch (Exception e) {
        }
        resetThongTin();
    }//GEN-LAST:event_thempbBTNMouseClicked

    private void tblphongbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphongbanMouseClicked
        int row = tblphongban.getSelectedRow();
        maphongbanTF.setText(phongbanDefaultTableModel.getValueAt(row, 0).toString());
        tenphongbanTF.setText(phongbanDefaultTableModel.getValueAt(row, 1).toString());
        diachiphongbanTF.setText(phongbanDefaultTableModel.getValueAt(row, 2).toString());
        sdtphongbanTF.setText(phongbanDefaultTableModel.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblphongbanMouseClicked

    private void maphongbanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maphongbanTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maphongbanTFActionPerformed

    private void tenphongbanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenphongbanTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenphongbanTFActionPerformed

    private void DanhSachPhongBanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachPhongBanBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DanhSachPhongBanBTNActionPerformed

    private void diachiphongbanTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diachiphongbanTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diachiphongbanTFActionPerformed

    private void suapbBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suapbBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suapbBTNActionPerformed

    private void timkiemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemCBActionPerformed
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLiPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLiPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLiPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLiPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new this.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DanhSachPhongBanBTN;
    private javax.swing.JTextField diachiphongbanTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maphongbanTF;
    private javax.swing.JTextField sdtphongbanTF;
    private javax.swing.JButton suapbBTN;
    private javax.swing.JTable tblphongban;
    private javax.swing.JTextField tenphongbanTF;
    private javax.swing.JButton thempbBTN;
    private javax.swing.JComboBox<String> timkiemCB;
    private javax.swing.JButton timkiempbBTN;
    private javax.swing.JButton xoapbBTN;
    // End of variables declaration//GEN-END:variables

    private void resetThongTin() {
        maphongbanTF.setText("");
        tenphongbanTF.setText("");
        diachiphongbanTF.setText("");
        sdtphongbanTF.setText("");
    }
}
