/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GiaoDien;

import DataBase.DataProvider;
import Dao.ChucVuDao;
import Model.ChucVu;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan
 */
public class QuanLyChucVu extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private ArrayList<ChucVu> CVList;
    DefaultTableModel chucvuDefaultTableModel;

    public QuanLyChucVu() {
        initComponents();
        chucvuDefaultTableModel = (DefaultTableModel) tblchucvu.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblchucvu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        macongviecTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tencongviecTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        themcvBTN = new javax.swing.JButton();
        suacvBTN = new javax.swing.JButton();
        xoacvBTN = new javax.swing.JButton();
        timkiemcvBTN = new javax.swing.JButton();
        danhsachcvBTN = new javax.swing.JButton();
        timkiemCB = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 255, 153));

        tblchucvu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tblchucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chức vụ", "Tên chức vụ"
            }
        ));
        tblchucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchucvuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblchucvu);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        macongviecTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Mã chức vụ");

        tencongviecTF.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tên chức vụ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(macongviecTF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tencongviecTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(macongviecTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tencongviecTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        themcvBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        themcvBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create-icon.png"))); // NOI18N
        themcvBTN.setText("Thêm");
        themcvBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themcvBTNMouseClicked(evt);
            }
        });

        suacvBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suacvBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-document-edit-icon-16.png"))); // NOI18N
        suacvBTN.setText("Sửa");
        suacvBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suacvBTNMouseClicked(evt);
            }
        });

        xoacvBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        xoacvBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-delete-icon.png"))); // NOI18N
        xoacvBTN.setText("Xoá");
        xoacvBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xoacvBTNMouseClicked(evt);
            }
        });
        xoacvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoacvBTNActionPerformed(evt);
            }
        });

        timkiemcvBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timkiemcvBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_search.png"))); // NOI18N
        timkiemcvBTN.setText(" Tìm kiếm ");
        timkiemcvBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemcvBTNMouseClicked(evt);
            }
        });
        timkiemcvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemcvBTNActionPerformed(evt);
            }
        });

        danhsachcvBTN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        danhsachcvBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-calendar-list-icon.png"))); // NOI18N
        danhsachcvBTN.setText("Hiển thị danh sách");
        danhsachcvBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachcvBTNMouseClicked(evt);
            }
        });

        timkiemCB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timkiemCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm theo mã chức vụ", "Tìm kiếm theo tên chức vụ" }));
        timkiemCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemCBMouseClicked(evt);
            }
        });
        timkiemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(themcvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suacvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoacvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(danhsachcvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiemcvBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timkiemCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(themcvBTN)
                .addGap(18, 18, 18)
                .addComponent(suacvBTN)
                .addGap(18, 18, 18)
                .addComponent(xoacvBTN)
                .addGap(18, 18, 18)
                .addComponent(danhsachcvBTN)
                .addGap(18, 18, 18)
                .addComponent(timkiemcvBTN)
                .addGap(18, 18, 18)
                .addComponent(timkiemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblchucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchucvuMouseClicked
        int row = tblchucvu.getSelectedRow();
        macongviecTF.setText(chucvuDefaultTableModel.getValueAt(row, 0).toString());
        tencongviecTF.setText(chucvuDefaultTableModel.getValueAt(row, 1).toString());

    }//GEN-LAST:event_tblchucvuMouseClicked

    private void themcvBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themcvBTNMouseClicked
        ChucVuDao cvd = new ChucVuDao();
        String ma = macongviecTF.getText();
        String name = tencongviecTF.getText();
        CVList = cvd.DSChucVu();
        try {
            if (ma.equals("") || name.equals("")) {
                JOptionPane.showMessageDialog(null, "Không được để trống !");
                return;
            }
            ChucVu chucVu = new ChucVu(ma, name);
            for (ChucVu cv : CVList) {
                if (chucVu.trungMa(cv)) {
                    JOptionPane.showMessageDialog(null, "Mã đã tồn tại . Vui lòng nhập mã khác !");
                    return;
                }
                if (chucVu.trungNameCv(cv)) {
                    JOptionPane.showMessageDialog(null, "Tên đã tồn tại . Vui lòng nhập tên khác !");
                    return;
                }

            }
            if (cvd.themchucvu(chucVu)) {
                JOptionPane.showMessageDialog(null, "Thêm thành công !");
                chucvuDefaultTableModel.addRow(chucVu.toObject());
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại ");
            }
        } catch (Exception e) {
        }
        resetThongTin();
    }//GEN-LAST:event_themcvBTNMouseClicked

    private void suacvBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suacvBTNMouseClicked
        ChucVuDao cvd = new ChucVuDao();
        ChucVu cv = new ChucVu();
        cv.setMaCV(macongviecTF.getText());
        cv.setNameCV(tencongviecTF.getText());

        if (macongviecTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập mã công việc !");
            macongviecTF.requestFocus();
        } else if (tencongviecTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hãy nhập tên công việc !");
            tencongviecTF.requestFocus();

        } else {
            if (cvd.updateChucVu(cv)) {
                JOptionPane.showMessageDialog(null, "Sửa Thành Công!");
                int i = tblchucvu.getSelectedRow();
                if (i >= 0) {
                    chucvuDefaultTableModel.setValueAt(tencongviecTF.getText(), i, 1);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
            }
            resetThongTin();
        }
    }//GEN-LAST:event_suacvBTNMouseClicked

    private void xoacvBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xoacvBTNMouseClicked
        ChucVuDao cvd = new ChucVuDao();
        ChucVu cv = new ChucVu();
        String macv = JOptionPane.showInputDialog(null, "Nhập mã công việc cần xoá");
        cv.setMaCV(macv);

        int remove = tblchucvu.getSelectedRow();
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có muốn xoá công việc có mã " + macv);

        try {
            if (confirm == JOptionPane.YES_OPTION) {
                if (cvd.xoaChucVu(macv)) {
                    JOptionPane.showMessageDialog(null, "Xoá thành công!");
                    chucvuDefaultTableModel.removeRow(remove);
                } else {
                    JOptionPane.showMessageDialog(null, "Xoá thất bại!");
                }
            } else {

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_xoacvBTNMouseClicked

    private void timkiemcvBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemcvBTNMouseClicked
        ChucVuDao cvd = new ChucVuDao();
        String choice = timkiemCB.getItemAt(timkiemCB.getSelectedIndex());
        if (choice.equals("Tìm kiếm theo mã công việc")) {
            String input = JOptionPane.showInputDialog(null, "Nhập mã công việc ");
            if (input != null && input.length() > 0) {
                if (cvd.timKiemMaCv(input) != null) {
                    chucvuDefaultTableModel.setRowCount(0);
                    chucvuDefaultTableModel.addRow(cvd.timKiemMaCv(input).toObject());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Mã công việc không tồn tại ! ");
                }
            }
        } else {
            String input = JOptionPane.showInputDialog(null, "Nhập tên công việc");
            if (input != null && input.length() > 0) {
                if (cvd.timkiemTenCv(input) != null) {
                    chucvuDefaultTableModel.setRowCount(0);
                    chucvuDefaultTableModel.addRow(cvd.timkiemTenCv(input).toObject());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Tên công việc không tồn tại ! ");
                }
            }
        }
    }//GEN-LAST:event_timkiemcvBTNMouseClicked

    private void timkiemcvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemcvBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemcvBTNActionPerformed

    private void danhsachcvBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachcvBTNMouseClicked
        ChucVuDao cvd = new ChucVuDao();
        CVList = cvd.DSChucVu();
        chucvuDefaultTableModel.setRowCount(0);
        CVList.forEach(s -> chucvuDefaultTableModel.addRow(s.toObject()));
    }//GEN-LAST:event_danhsachcvBTNMouseClicked

    private void timkiemCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemCBMouseClicked

    }//GEN-LAST:event_timkiemCBMouseClicked

    private void xoacvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoacvBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xoacvBTNActionPerformed

    private void timkiemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton danhsachcvBTN;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField macongviecTF;
    private javax.swing.JButton suacvBTN;
    private javax.swing.JTable tblchucvu;
    private javax.swing.JTextField tencongviecTF;
    private javax.swing.JButton themcvBTN;
    private javax.swing.JComboBox<String> timkiemCB;
    private javax.swing.JButton timkiemcvBTN;
    private javax.swing.JButton xoacvBTN;
    // End of variables declaration//GEN-END:variables

    private void resetThongTin() {
        macongviecTF.setText("");
        tencongviecTF.setText("");
    }
}
