/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Dao.LuongDao;
import Model.Luong;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LONGDT
 */
public class UserLuong extends javax.swing.JPanel {

    /**
     * Creates new form UserLuong
     */
    private ArrayList<Luong> LList;
    DefaultTableModel luongDefaultTableModel;
    public UserLuong() {
        initComponents();
        luongDefaultTableModel = (DefaultTableModel) tblLuong.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        btnTimkiem = new javax.swing.JButton();
        cbLuong = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 204));

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bậc lương", "Lương cơ bản", "Thưởng"
            }
        ));
        jScrollPane1.setViewportView(tblLuong);

        btnTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_search.png"))); // NOI18N
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        cbLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm Kiếm theo bậc lương", "Tìm kiếm theo lương cơ bản" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbLuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimkiem)
                    .addComponent(cbLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        LuongDao ld = new LuongDao();
        String choice = cbLuong.getItemAt(cbLuong.getSelectedIndex());
        if (choice.equals("Tìm Kiếm theo bậc lương")) {
            String input = JOptionPane.showInputDialog(null, "Nhập bậc lương ");
            if (input != null && input.length() > 0) {
                if (ld.timKiemBacLuong(Integer.parseInt(input)) != null) {
                    luongDefaultTableModel.setRowCount(0);
                    luongDefaultTableModel.addRow(ld.timKiemBacLuong(Integer.parseInt(input)).toObjects());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Bậc lương không tồn tại ! ");
                }
            }
        } else if (choice.equals("Tìm kiếm theo lương cơ bản")){
            String input = JOptionPane.showInputDialog(null, "Nhập lương cơ bản");
            if (input != null && input.length() > 0) {
                if (ld.timKiemBacLuong(Integer.parseInt(input)) != null) {
                    luongDefaultTableModel.setRowCount(0);
                    luongDefaultTableModel.addRow(ld.timKiemLuongCB(Integer.parseInt(input)).toObjects());
                    JOptionPane.showMessageDialog(null, "Tìm thành công ! ");
                } else {
                    JOptionPane.showMessageDialog(null, "lương cơ bản không tồn tại ! ");
                }
            }
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JComboBox<String> cbLuong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLuong;
    // End of variables declaration//GEN-END:variables
}
