/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Dao.*;
import Model.NhanVien;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LONGDT
 */
public class UserNhanVien extends javax.swing.JPanel {
    DefaultTableModel tblModel;
    /**
     * Creates new form UserNhanVien
     */
    public UserNhanVien() {
        initComponents();
        loadComboBox();
        initTable();
    }
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"MANV", "USERNAME", "NAMENV", "MAIL", "PHONE", "CHUCVU", "BACLUONG", "PHONGBAN", "HDLD"});
        tblNhanVien.setModel(tblModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        cbSearch = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));

        cbSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn_search.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NV.jpg"))); // NOI18N

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        NhanVienDao nvd = new NhanVienDao();
        String choice = cbSearch.getItemAt(cbSearch.getSelectedIndex());
        if(choice.equals("Tìm kiếm theo mã nhân viên")){
            tblModel.setRowCount(0);
            String input = JOptionPane.showInputDialog(null, "Nhập mã nhân viên ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoMaNV(input);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại ! ");
                    }
                }
            }
        }else if(choice.equals("Tìm kiếm theo chức vụ")){
            String input = JOptionPane.showInputDialog(null, "Nhập mã chức vụ ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoChucVu(input);
                tblModel.setRowCount(0);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Mã chức vụ không tồn tại ! ");
                    }
                }
            }
        }else if(choice.equals("Tìm kiếm theo bậc lương")){
            String input = JOptionPane.showInputDialog(null, "Nhập bậc lương ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoBacLuong(input);
                tblModel.setRowCount(0);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Bậc lương không tồn tại ! ");
                    }
                }
            }
        }else if(choice.equals("Tìm kiếm theo phòng ban")){
            String input = JOptionPane.showInputDialog(null, "Nhập mã phòng ban ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoPhongBan(input);
                tblModel.setRowCount(0);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Mã phòng ban không tồn tại ! ");
                    }
                }
            }
        }else if(choice.equals("Tìm kiếm theo hợp đồng lao động")){
            String input = JOptionPane.showInputDialog(null, "Nhập hợp đồng lao động ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoHDLD(input);
                tblModel.setRowCount(0);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Hợp đồng lao động không tồn tại ! ");
                    }
                }
            }
        }else if(choice.equals("Tìm kiếm theo tên nhân viên")){
            String input = JOptionPane.showInputDialog(null, "Nhập tên nhân viên ");
            if(input != null && input.length() > 0){
                List<NhanVien> li = nvd.timKiemTheoNameNV(input);
                tblModel.setRowCount(0);
                for(NhanVien nv: li){
                    if(nv != null){
                        tblModel.addRow(nv.toObjects1());
                    }else {
                        JOptionPane.showMessageDialog(null, "Tên nhân viên không tồn tại ! ");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    private void loadComboBox(){
        cbSearch.removeAllItems();
        cbSearch.addItem("Tìm kiếm theo mã nhân viên");
        cbSearch.addItem("Tìm kiếm theo chức vụ");
        cbSearch.addItem("Tìm kiếm theo bậc lương");
        cbSearch.addItem("Tìm kiếm theo phòng ban");
        cbSearch.addItem("Tìm kiếm theo hợp đồng lao động");
        cbSearch.addItem("Tìm kiếm theo tên nhân viên");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblNhanVien;
    // End of variables declaration//GEN-END:variables
}
